- README.md
Added content for beginner questions
> Add content beginner for readme

- README.md
fix some mistakes:
- unordered list
- trailing-spaces
- multiple-blanks
> Lint issues

- README.md
According to what I read I found these few corrections.
> ADD: Some corrections to the Readme

- README.md
Respondo pregunta "¿Qué son las refs en React?" y unifico con "¿Qué es el hook useRef?"
> Corrijo pregunta vacía y unifico lógica

- README.md
- Explicación de los corchetes en JSX
- Más información relevante sobre useState
- Solución al importar librería con un nombre distinto al que se usa después.
> Algunos cambios y datos relevantes que considero :)

- README.md
Agrego referencia al índice al final de cada respuesta para evitar tener que scrollear hasta arriba si estoy en alguna pregunta del medio o llegando al final.
Adjunto preview:
> Feature: Referencia al índice en cada respuesta.

- README.md
Mencionar que no solo se volverá a ejecutar el mensaje cada vez que cambie el valor de `count` si no que también al momento de cargar el componente.
PD: Mis felicitaciones por el gran trabajo de crear este repositorio 🥳 sin duda una ayuda muy valiosa para personas que recién comienzan con React o también para personas con cierta expertis que quieran  o necesiten reforzar algunos puntos.
> Improve the explanation of "¿Qué hace el hook useEffect?"

- README.md
Usar lista para mencionar casos de usos.
> Use list to define use cases of `useEffect`

- README.md
> fix: ButtonSecondary({children})

- README.md
Agrego signo de pregunta que faltaba tanto en índice como en título.
Antes.
Ahora.
> Fix: fixing missing question mark.

- README.md
Hola miduu el repo está quedando genial!
Modifiqué el título del `índice` y su `link` para que coincidiera con el del artículo!
Muchas gracias por todo el contenido!! Hay mucha calidad y está quedando genial 😊
> fix title in index

- README.md
Hola midu 👋
Me pareció interesante agregar una nueva sección llamada: Errores Típicos en React.
Agregué esta sección y coloqué una pregunta nueva.
Estoy atenta a cualquier observación ✌🏻
> Added section: Common React Errors and a new question for this section

- README.md
Holaaa 👋 
El sub-link `¿Qué quiere decir: Warning: Each child in a list should have a unique key prop?` del módulo [Errores Típicos en React](https://github.com/midudev/preguntas-entrevista-react#errores-t%C3%ADpicos-en-react) no direccionaba correctamente por algunos caracteres de interrogación dentro del propio link.
Se removieron esos caracteres y quedó para lamerlo! ❤️
> Fix title path in index

- README.md
I saw it pertinent to add how this hook useId works in the beginner's section due to the complexity of the hook.
> add-hook-useID

- README.md
Se agregó una nueva pregunta en la sección de: Errores Típicos en React.
Nueva pregunta: Too many re-renders. React limits the number of renders to prevent an infinite loop
> Added new common error

- README.md
Agregar todos los inicializares de React más populares, para ello se agrego Nextjs, Gatsby y Create React App. Se agregaron en orden de popularidad según https://npmtrends.com/@vitejs/plugin-react-vs-create-react-app-vs-gatsby-vs-next
> Add more React initializers

- README.md
*No se agregó pregunta*
Agrego ejemplo de como si funciona condicionales en componentes
Arreglo enlaces de la parte inferior dirigidos a "useState" y "useEffect"
Arreglo de ejemplo en "AbortController"
Corrección en estilo del archivo:
- espacios en blanco
- mas de una línea en la separación
- nombre de componente
- tildes
> Corrección de enlaces, acentos, y ejemplos

- README.md
Question about, what does the hook useLayoutEffect do?
I have included a question about what the Hook useLayoutEffect is and how it works.
> useLayoutEffect

- .gitignore
- README.md
- pull_request_template.md
Se agregó una nueva pregunta en la sección principiantes.
Nueva pregunta: ¿Qué es el Compound Components Pattern?
La pregunta tiene un concepto breve y un ejemplo sencillo para que cualquiera lo pueda entender. 
Además, cuenta con enlaces de interés sobre el tema. 
- package-lock added to .gitignore
- unnecessary spaces removed from pull_request_template.md
> Compound Components Pattern

- README.md
- pull_request_template.md
> Bugfix - Se añaden tildes :heavy_check_mark: 

- app/[post]/page.js
Añade un enlace a la pregunta anterior y la siguiente en el footer.
Closes #53
> Add previous and next question in footer

- README.md
> Add accent to "líneas"

- README.md
Agregue un nuevo enlace de interés apuntando a la documentación actualizada de react en la pregunta **¿Que es React?**
> add a new link to the first question

- README.md
He arreglado un par de errores de tipografía en el ejemplo de [¿Qué es flushSync en React?](https://github.com/midudev/preguntas-entrevista-react#qu%C3%A9-es-flushsync-en-react): en `// component ha sido re-renderizado y el DOM ha sido actualizada ✅` he corregido `actualizado`.
> Fix flushSync example typo

- README.md
Agregué un signo de interrogación de cierre en muchas preguntas que no lo tenían.
> Fix closing question marks

- app/components/Header.jsx
Se realizo el fix para el issue #69 haciendo el cambio en el useEffect para que no solo se ejecute en la primera carga, esto soluciona el contador para que sea actualizado sin hacer un full refresh
> Fix read counter

- app/components/Header.jsx
> fix: Autocomplete component in dark-mode

- README.md
Explicación sobre el propósito del atributo "key" en React y su importancia al renderizar listas de elementos.
Por favor incluye una descripción breve de tus cambios
> Añadir explicación sobre el atributo "key" en React

- app/components/Header.jsx
- app/components/Stars.jsx
> Fix stars counter; Bug with Search component in darkmode
